apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ta-front
  labels:
    run: ta-front
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: ta-front
    spec:
      containers:
        - image: icn.ocir.io/cn0vhjsmelc3/travel-agency/travel-agency-front:latest
          imagePullPolicy: Always 
          name: ta-front
          ports:
            - containerPort: 8000 
              protocol: TCP
      restartPolicy: Always
      imagePullSecrets:
        - name: ocirsecret